### ISSUE TITLE
changing app-scrim z-index?

### ISSUE THREAD

**Issue by robdodson** [PolymerLabs/app-layout#10]
is there a way to style the app-scrim inside the app-drawer-layout with a custom property? Because the z-index is quite low, I have other elements on my page which are appearing above it now.

**Comment by blasten** [comment]
sorry for the late response. This is certainly an issue. Is that z-index required?

**Comment by robdodson** [comment]
the z-index in app-scrim? you tell me! :P

my elements did need a z-index. this was so long ago i don't recall what i was trying to do though :\

**Comment by frankiefu** [comment]
I don't think we are setting `z-index` on the scrim anymore.  This may not be an issue now.

**Comment by robdodson** [comment]
ok closing then :)

**Comment by blasten** [comment]
I believe the issue is that if any of your elements use z-indexes, this issue will persist. We don't use z-indexes to avoid creating stacking contexts, so there's no way to enforce that your element should be behind the scrim. The moment any of your element has a `position:absolute/relative` and `z-index!=auto`, you hit this problem. I think this is still an issue.

**Comment by robdodson** [comment]
Ah yes. Thank you @blasten you're correct. Sorry, my memory of the original issue is foggy because it was a few months ago.

**Comment by blasten** [comment]
haha no worries 🙏

**Comment by frankiefu** [comment]
With the current `app-drawer` you should be able to set `z-index` on the `app-drawer` and that will make both the scrim and the drawer content above the other elements which have `z-index > 0`.  Please reopen if this is still an issue.
