### ISSUE TITLE
0.0.15 breaks paper-dialog with backdrop

### ISSUE THREAD

**Issue by rbjarnason** [PolymerLabs/app-layout#155]
When I upgraded to master - paper-dialog shows up behind the overlay backdrop and is not accessible. Downgrading to 0.0.14 fixed the problem. Wanted to let you know, unfortunately I don't have the time to debug.  Loving app-layout btw :)

**Comment by keanulee** [comment]
To fix #109, we had to force `<app-header-layout>` to create a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) for the content. That means that any content in `<app-header-layout>` will be confined to that stacking context. `<paper-dialog>` creates the backdrop as a child of body, so that's why the dialog is appearing below it.

There are at least two alternatives to fix this:

- Put `<paper-dialog>` outside of any non-root stacking context (i.e. as a child of `<body>`, or at least outside of `<app-header-layout>`)
- Don't use `<app-header-layout>` and set `z-index` on `<app-header>` yourself.

**Comment by frankiefu** [comment]
This is a known issue in `paper-dialog`, see: https://github.com/PolymerElements/paper-dialog-behavior/issues/78 and https://github.com/PolymerElements/paper-dialog/issues/44#issuecomment-172013206

**Comment by rbjarnason** [comment]
Thanks :)

**Comment by rbjarnason** [comment]
@keanulee One question, I have a behavior that I have used in the past, over a year ago, to reparent paper-dialog.  This does not seem to work any more.

Any ideas?

```javascript
Polymer.MoveDialogToTop = {
    moveDialogToTopDom: function(name) {
      if (open) {
        var node = document.querySelector('#'+name);
        if (node) {
          var textnode = document.querySelector("body");
          textnode.appendChild(node);
        } else {
          console.error("Can't find node to move to body");
        }
      }
    }
  };
```

Any hints?

**Comment by keanulee** [comment]
@rbjarnason If you are using Shadow DOM, `document.querySelector('#'+name)` might not work for you since `querySelector` doesn't go through shadow roots. I would suggest passing a reference to the node itself instead of an element ID:

```javascript
moveDialogToBody = function(node) {
  if (node) document.body.appendChild(node);
}
```

Usage (from inside an element):

```javascript
var nodeToMove = this.$.someLocalDomId; // or Polymer.dom(this.root).querySelector('.some-local-dom-selector')
moveDialogToBody(nodeToMove);
```

**Comment by rbjarnason** [comment]
Thanks for this @keanulee - this sort of works, the paper-dialog is accessible but it looses its styling and behaves strangely as in if you click anywhere except on paper-input it closes itself....

However if I move 'this' on the element that contains paper-dialog everything seems to be working fine:

```javascript
  this.moveDialogToBody(this);
  this.$.editDialog.open();
```
Do you see in any problems with this approach?

**Comment by keanulee** [comment]
@rbjarnason If the structure of your app allows the your dialog container element to be in body, then it would be better if it was there in the first place (instead of moving it). If you need to show a dialog from within an element, then maybe communicate that up the tree (through `notify`ing properties and/or events).

**Comment by rbjarnason** [comment]
@keanulee I think I will move them all to a dialog-container in the body. I have a relatively large app so this will be quite a bit of refactoring work but I agree its safer to do it like this.  Moving the element that has data-bindings and stuff will probably cause unexpected problems. Thanks again for your help.
