### ISSUE TITLE
app-header width doesn't update

### ISSUE THREAD

**Issue by aydun1** [PolymerLabs/app-layout#53]
On Chrome desktop (and possibly other browsers), in layouts featuring app-header, if the scrollbar is added or removed, the width of the header doesn't update to reflect this.

To reproduce (although a bit tedious), go to [Pesto](http://polymerlabs.github.io/app-layout/templates/pesto/), and with developer tools, delete cards until the scrollbar disappears.

White-space will remain where the scrollbar previously was.

Resizing the browser window fixes this, as does `document.querySelector('app-header').resetLayout();`, for example.

Is this a bug, or should I be calling `resetLayout()` after making changes to my page that could affect the scrollbar?

**Comment by ralcar** [comment]
I have a similar problem, where im using the Pesto app as a template. I put a neon-animated-pages in, instead of the iron-pages, and whenever i resize, the app-header behaves weird. It wont strech more than a certain width, and when the drawer closes, it doesnt fill the space on the left side of the header.

Using your resetLayout helped though

**Comment by blasten** [comment]
That's right. you would need to call `resetLayout()`or implement the iron-resizable behavior https://github.com/PolymerElements/iron-resizable-behavior. That way the header would get a notification when changes to the content should update the layout.

**Comment by ralcar** [comment]
That totally worked, thank you!!!
