### ISSUE TITLE
Scroll bar disapear when app-drawer is showing

### ISSUE THREAD

**Issue by moduv5** [PolymerLabs/app-layout#97]
When we open the drawer, the scroll bar disappear on the site’s content leading to app-header not resizing and unexpected issue on layout. For example, I have a layout with one item per row but when I open the app-drawer it displays on two rows because the scroll-bar disappear. You can see this problem in the demo2.html file when you are on a mobile size. Here is images of the bug in my app:

When the app drawer is close: 

![image](https://cloud.githubusercontent.com/assets/6440586/13499362/fc61e50e-e12b-11e5-905b-549d46b8d3d3.png)

When I open the drawer: 

![image](https://cloud.githubusercontent.com/assets/6440586/13499387/2dc65706-e12c-11e5-9c5a-73e8da896350.png)

You can see that the app-header have not resized and that the content is now display two card per rows.

**Comment by frankiefu** [comment]
The scrollbar disappears because the `app-drawer` is setting `overflow: hidden` on the body to prevent the content below the backdrop to scroll when the drawer is opened.  So the scrollbar disappears is expected and the layout will change because of that, but the `app-header` should resize to fill the empty gap and that's a bug.

**Comment by blasten** [comment]
fixed in master

**Comment by xelra** [comment]
@blasten Can this be reopened? Apparently it unfixed itself.

When I open the drawer in the polymer starter kit from Polymer 2, this issue is gone. The scrollbar stays and the content behind the drawer does not jump around.

But in the pwa starter kit from Polymer 3, the scrollbar vanishes and the content jumps around.

**Comment by keanulee** [comment]
The fix to this issue is not the same as https://github.com/Polymer/pwa-starter-kit/issues/98 - specifically, this one and the fix refers to how the header doesn't resize after the scrollbar disappears. The scrollbar disappearing is a side effect of making `body.style.overflow = 'hidden'` which is necessary to block scrolling when the drawer is opened. https://github.com/PolymerElements/app-layout/issues/375 is a related issue.

**Comment by xelra** [comment]
I'm confused. In the polymer starter kit the scroll doesn't disappear and neither does the content below the drawer scroll when I turn the mouse-wheel.

Something just doesn't make sense on why this is happening now in the pwa starter kit. If it's the same elements, then how was it fixed in 2.0?

**Comment by keanulee** [comment]
pwa-starter-kit !== polymer-starter-kit. polymer-starter-kit uses an element scroller (and `body.style.overflow = 'hidden'` doesn't hide the element scroller's scrollbar) while pwa-starter-kit uses the document scroller.

**Comment by xelra** [comment]
Thanks, now it makes sense.

So where does this need fixing? In app-layout or in the pwa-starter-kit?

I can't imagine this being ok for anyone designing a web app.

**Comment by keanulee** [comment]
We're not going to fix this in pwa-starter-kit because we're optimizing for the experience on mobile (which uses the document scroller so that the browser's URL toolbar scrolls away and doesn't have visible scrollbars). Even some desktop browsers don't show the scrollbar so this won't matter there. If you need to keep the scrollbar, you'll need to create an element scroller for the content that is the height of the viewport (e.g. `height: 100vh; overflow: auto`), but note you'll hurt mobile browsers (i.e. the URL toolbar will not scroll away).
